# Generated by Django 3.1.4 on 2020-12-09 02:18

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for row in Product.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

    Shop = apps.get_model('shop', 'Shop')
    for row in Shop.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201209_0918'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
