# Generated by Django 3.1.4 on 2020-12-09 16:11

import autoslug.fields
import bloom.utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201209_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=700, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(max_length=500, upload_to=bloom.utils.paths.get_photo_path),
        ),
    ]
