# Generated by Django 3.1.4 on 2020-12-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201209_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='productrating',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
