# Generated by Django 3.1.4 on 2020-12-15 03:50

import autoslug.fields
import bloom.utils.paths
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201211_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, upload_to=bloom.utils.paths.get_shop_path),
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, null=True, editable=False, max_length=400, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shopcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shop.ShopCategory'),
        ),
    ]
