# Generated by Django 3.1.4 on 2020-12-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201215_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'Shop categories'},
        ),
        migrations.AddField(
            model_name='shop',
            name='apartment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
