# Generated by Django 3.1.4 on 2021-01-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210107_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='subscriber',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
