# Generated by Django 3.1.4 on 2021-01-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_shop_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
