# Generated by Django 3.1.4 on 2021-01-10 13:22

import bloom.utils.paths
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210110_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=bloom.utils.paths.get_photo_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', unique=True),
        ),
    ]
