# Generated by Django 3.1.4 on 2021-01-19 09:42
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_shop_location'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
