# Generated by Django 3.1.4 on 2020-12-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopper_share_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shopper_sms_update',
            field=models.BooleanField(default=True),
        ),
    ]
