# Generated by Django 3.1.4 on 2021-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_shippingaddress_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
