# Generated by Django 3.1.4 on 2021-01-22 09:24

from django.db import migrations, models


def update_order_status(apps, schema_editor):
    Order = apps.get_model('order', 'Order')
    Order.objects.filter(status='pending').update(status="awaiting_payment")
    Order.objects.filter(status='succeed').update(status="awaiting_shipment")


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210115_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('awaiting_shipment', 'Awaiting shipment'), ('on_hold', 'On hold'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=20),
        ),
        migrations.RunPython(update_order_status, reverse_code=migrations.RunPython.noop),
    ]
