# Generated by Django 3.1.4 on 2021-01-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210122_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('awaiting_shipment', 'Awaiting shipment'), ('payment_cancelled', 'Payment cancelled'), ('on_hold', 'On hold'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=20),
        ),
    ]
