# Generated by Django 3.1.4 on 2021-02-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210122_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, default='native', max_length=50),
        ),
    ]
