# Generated by Django 3.1.4 on 2021-02-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='channel',
            field=models.CharField(choices=[('website', 'Website'), ('google_shop', 'Google Shopping')], default='website', max_length=20),
        ),
    ]
