# Generated by Django 3.0.11 on 2020-11-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role_type',
            field=models.CharField(blank=True, choices=[(0, 'Admin'), (1, 'Vendor'), (2, 'Shopper')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='store_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
