# Generated by Django 3.1.4 on 2020-12-07 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201203_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store_type',
        ),
        migrations.AddField(
            model_name='mycollection',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mycollection',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='locality',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mycollection',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='FollowedShops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('shops', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='mycollection',
            name='product',
        ),
    ]
