# Generated by Django 3.1.4 on 2020-12-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_wishlist_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='charges_enabled',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100),
        ),
    ]
