# Generated by Django 3.1.4 on 2021-01-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_shopifyconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='love_shops',
        ),
    ]
