# Generated by Django 3.1.7 on 2021-02-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_wordpressshop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopifyApp',
            new_name='ShopifyShop',
        ),
    ]
